Settings: Fix RuntimeException in InputMethod Settings
Issue-Id: RM-170

Fixes:
java.lang.RuntimeException: Unable to resume activity
{com.android.settings/com.android.settings.SubSettings}:
java.lang.NullPointerException: Attempt to invoke virtual
method 'void android.preference.Preference.onPrepareForRemoval()'
on a null object reference

OnResume calls the method changed with an already removed preference
-> results in null being passed and therefore NPE occurs

Change-Id: Idfca3a79aaaac71dfc872bb012b5fd1b2c247341